name: Build Zalo for Linux

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      zalo_version:
        description: 'Zalo Version (leave empty for latest)'
        required: false
        default: ''
        type: string
      zadark_version:
        description: 'ZaDark Version/Tag/Commit (leave empty for latest)'
        required: false
        default: ''
        type: string

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Update ZaDark submodule
      run: |
        git submodule update --remote plugins/zadark

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Cache Electron binaries
      uses: actions/cache@v3
      with:
        path: ~/.cache/electron
        key: ${{ runner.os }}-electron-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-electron-
          
    - name: Install Node.js dependencies
      run: npm ci --prefer-offline --no-audit

    - name: Setup and Build
      env:
        ZALO_VERSION: ${{ github.event.inputs.zalo_version }}
        ZADARK_VERSION: ${{ github.event.inputs.zadark_version }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npm run setup
        npm run build